#pragma once
#include <juce_audio_formats/juce_audio_formats.h>
#include <juce_dsp/juce_dsp.h>
#include <array>
#include <vector>

// Loads the 16 original DW-8000 DWGS waveforms from WAV files and builds
// band-limited octave tables for alias-free playback at any host sample rate.
class DWGSWavetableBank
{
public:
    static constexpr int NUM_WAVEFORMS    = 16;
    static constexpr int MASTER_SIZE      = 4096;  // Starsky Sounds WAV frame count
    static constexpr int TABLE_SIZE       = 4096;  // working table (same for best quality)
    // 2 bands per octave (every 6 semitones = √2 ratio) × 9 octaves.
    // Finer granularity means each table is bandlimited much closer to the actual
    // note frequency, drastically reducing aliasing in the upper half of each band.
    static constexpr int BANDS_PER_OCTAVE = 2;
    static constexpr int NUM_OCTAVE_BANDS = 18;    // C0(16Hz)..~C9(8kHz)

    // tables[waveform 0..15][octave 0..8]
    // Each inner array has TABLE_SIZE+1 samples (extra sample = wrap-around for interpolation)
    using OctaveTable  = std::array<float, TABLE_SIZE + 1>;
    using WaveformTables = std::array<OctaveTable, NUM_OCTAVE_BANDS>;
    std::array<WaveformTables, NUM_WAVEFORMS> tables{};

    bool loaded = false;

    // Load from the BinaryData symbols generated by CMake juce_add_binary_data.
    // Returns true on success. Pass the actual host sample rate for correct
    // band-limiting (defaults to 48 kHz for offline / first-call cases).
    bool loadFromBinaryData(float hostSampleRate = 48000.0f);

    // Fallback: load from a directory containing "DW8000 1.wav" .. "DW8000 16.wav"
    bool loadFromDirectory(const juce::File& dir);

    // Pick the right octave band table for a given frequency
    const OctaveTable& tableForFreq(int waveformIndex, float freqHz) const;

private:
    // Decode one mono 16-bit WAV into a master float buffer
    bool decodeWAV(const void* data, size_t byteSize,
                   std::array<float, MASTER_SIZE>& out);

    // Build all NUM_OCTAVE_BANDS band-limited tables from a 4096-sample master cycle
    void buildBandLimitedTables(int waveformIdx,
                                const std::array<float, MASTER_SIZE>& master,
                                float hostSampleRate = 48000.0f);

    // FFT objects — allocated during build, not kept around
    static std::vector<float> zeroPadAndFFT(const float* src, int srcLen, int fftOrder);
    static void ifftToTable(std::vector<float>& spectrum, int fftOrder,
                            OctaveTable& out);
};
