#include "DWGSWavetableBank.h"
#include "DW8000WavetableData.h"    // generated by juce_add_binary_data
#include <cmath>
#include <algorithm>
#include <complex>

// ─── Reference frequencies for each band ──────────────────────────────────
// BANDS_PER_OCTAVE = 2, so bands step every 6 semitones (every √2 in frequency).
// Band 0 = C0 (~16 Hz), band 1 = F#0 (~23 Hz), band 2 = C1 (~33 Hz), …
static float bandRootFreq(int band)
{
    return 16.3516f * std::pow(2.0f, (float)band / DWGSWavetableBank::BANDS_PER_OCTAVE);
}

// ─── WAV decode ───────────────────────────────────────────────────────────
bool DWGSWavetableBank::decodeWAV(const void* data, size_t byteSize,
                                   std::array<float, MASTER_SIZE>& out)
{
    // Heap-allocate so the AudioFormatReader can take ownership and safely delete it.
    auto* stream = new juce::MemoryInputStream(data, byteSize, false);
    juce::WavAudioFormat fmt;
    std::unique_ptr<juce::AudioFormatReader> reader(
        fmt.createReaderFor(stream, true));  // true = reader owns stream

    if (!reader
        || reader->numChannels      != 1
        || reader->bitsPerSample    != 16
        || reader->lengthInSamples  != MASTER_SIZE)
        return false;

    juce::AudioBuffer<float> buf(1, MASTER_SIZE);
    reader->read(&buf, 0, MASTER_SIZE, 0, true, false);

    auto* src = buf.getReadPointer(0);
    for (int i = 0; i < MASTER_SIZE; ++i)
        out[i] = src[i];

    return true;
}

// ─── Band-limited table builder ───────────────────────────────────────────
// We use JUCE's FFT to remove harmonics above Nyquist for each octave.
// The master waveform was recorded at 44100 Hz but represents one cycle only
// (no time-domain sample rate meaning for the wavetable itself).
// We treat it as one period and zero harmonics above the aliasing threshold.

void DWGSWavetableBank::buildBandLimitedTables(int wi,
    const std::array<float, MASTER_SIZE>& master,
    float hostSampleRate)
{
    // FFT order for MASTER_SIZE = 4096 = 2^12
    constexpr int FFT_ORDER = 12;
    juce::dsp::FFT fft(FFT_ORDER);

    // performRealOnlyForwardTransform reads N real samples from buf[0..N-1]
    // and writes N complex pairs back to buf[0..2N-1] (interleaved re/im).
    std::vector<float> fftBuf(MASTER_SIZE * 2, 0.0f);
    for (int i = 0; i < MASTER_SIZE; ++i)
        fftBuf[i] = master[i];   // real samples at positions 0..N-1

    fft.performRealOnlyForwardTransform(fftBuf.data(), true);

    for (int band = 0; band < NUM_OCTAVE_BANDS; ++band)
    {
        float rootFreq  = bandRootFreq(band);
        // topFreq = highest frequency this table will be used for.
        // With BANDS_PER_OCTAVE=2 each band spans one tritone, so the top is
        // rootFreq × 2^(1/BANDS_PER_OCTAVE).  We must bandlimit to THIS value
        // or harmonics will alias for notes at the top of the band.
        float topFreq   = bandRootFreq(band + 1);  // next band's root = top of this band
        float nyquist   = hostSampleRate * 0.5f;
        // Guarantee zero aliasing for ALL pitches in the band (top-of-band limit)
        int   maxHarm   = std::max(1, (int)(nyquist / topFreq));
        // Cap at Nyquist of the 44100 Hz source recording
        int   recordMax = std::max(1, (int)(22050.0f / topFreq));
        maxHarm = std::min(maxHarm, recordMax);
        // Don't need more than MASTER_SIZE/2 harmonics
        maxHarm = std::min(maxHarm, MASTER_SIZE / 2);

        // Copy spectrum and zero unwanted harmonics
        std::vector<float> spec = fftBuf;
        for (int h = maxHarm + 1; h < MASTER_SIZE / 2; ++h)
        {
            spec[h * 2]     = 0.0f;  // real
            spec[h * 2 + 1] = 0.0f;  // imag
            // Mirror (negative frequencies)
            int mirrorIdx = MASTER_SIZE - h;
            if (mirrorIdx > 0 && mirrorIdx < MASTER_SIZE)
            {
                spec[mirrorIdx * 2]     = 0.0f;
                spec[mirrorIdx * 2 + 1] = 0.0f;
            }
        }

        // Inverse FFT
        fft.performRealOnlyInverseTransform(spec.data());

        // performRealOnlyInverseTransform writes N real samples to spec[0..N-1].
        float peak = 1e-9f;
        for (int i = 0; i < MASTER_SIZE; ++i)
            peak = std::max(peak, std::abs(spec[i]));

        auto& tbl = tables[wi][band];
        float scale = 1.0f / peak;
        for (int i = 0; i < TABLE_SIZE; ++i)
            tbl[i] = spec[i] * scale;

        // Wrap-around sample for linear interpolation
        tbl[TABLE_SIZE] = tbl[0];
    }
}

// ─── Pick correct band ────────────────────────────────────────────────────
const DWGSWavetableBank::OctaveTable&
DWGSWavetableBank::tableForFreq(int wi, float freqHz) const
{
    // band = floor(BANDS_PER_OCTAVE * log2(freqHz / C0))
    // With BANDS_PER_OCTAVE=2 this gives a band every 6 semitones.
    int band = (int)std::floor(BANDS_PER_OCTAVE * std::log2(freqHz / 16.3516f));
    band = std::clamp(band, 0, NUM_OCTAVE_BANDS - 1);
    return tables[wi][band];
}

// ─── Load from CMake BinaryData ───────────────────────────────────────────
bool DWGSWavetableBank::loadFromBinaryData(float hostSampleRate)
{
    struct Entry { const char* data; int size; };

    // The CMake juce_add_binary_data() replaces spaces with underscores
    // and appends the size variable with "Size" suffix.
    const Entry entries[NUM_WAVEFORMS] = {
        { DW8000WavetableData::DW8000_1_wav,  DW8000WavetableData::DW8000_1_wavSize  },
        { DW8000WavetableData::DW8000_2_wav,  DW8000WavetableData::DW8000_2_wavSize  },
        { DW8000WavetableData::DW8000_3_wav,  DW8000WavetableData::DW8000_3_wavSize  },
        { DW8000WavetableData::DW8000_4_wav,  DW8000WavetableData::DW8000_4_wavSize  },
        { DW8000WavetableData::DW8000_5_wav,  DW8000WavetableData::DW8000_5_wavSize  },
        { DW8000WavetableData::DW8000_6_wav,  DW8000WavetableData::DW8000_6_wavSize  },
        { DW8000WavetableData::DW8000_7_wav,  DW8000WavetableData::DW8000_7_wavSize  },
        { DW8000WavetableData::DW8000_8_wav,  DW8000WavetableData::DW8000_8_wavSize  },
        { DW8000WavetableData::DW8000_9_wav,  DW8000WavetableData::DW8000_9_wavSize  },
        { DW8000WavetableData::DW8000_10_wav, DW8000WavetableData::DW8000_10_wavSize },
        { DW8000WavetableData::DW8000_11_wav, DW8000WavetableData::DW8000_11_wavSize },
        { DW8000WavetableData::DW8000_12_wav, DW8000WavetableData::DW8000_12_wavSize },
        { DW8000WavetableData::DW8000_13_wav, DW8000WavetableData::DW8000_13_wavSize },
        { DW8000WavetableData::DW8000_14_wav, DW8000WavetableData::DW8000_14_wavSize },
        { DW8000WavetableData::DW8000_15_wav, DW8000WavetableData::DW8000_15_wavSize },
        { DW8000WavetableData::DW8000_16_wav, DW8000WavetableData::DW8000_16_wavSize },
    };

    for (int i = 0; i < NUM_WAVEFORMS; ++i)
    {
        std::array<float, MASTER_SIZE> master{};
        if (!decodeWAV(entries[i].data, (size_t)entries[i].size, master))
            return false;
        buildBandLimitedTables(i, master, hostSampleRate);
    }

    loaded = true;
    return true;
}

// ─── Load from directory (development fallback) ───────────────────────────
bool DWGSWavetableBank::loadFromDirectory(const juce::File& dir)
{
    for (int i = 1; i <= NUM_WAVEFORMS; ++i)
    {
        auto file = dir.getChildFile("DW8000 " + juce::String(i) + ".wav");
        if (!file.existsAsFile()) return false;

        juce::MemoryBlock mb;
        file.loadFileAsData(mb);

        std::array<float, MASTER_SIZE> master{};
        if (!decodeWAV(mb.getData(), mb.getSize(), master))
            return false;

        buildBandLimitedTables(i - 1, master);
    }

    loaded = true;
    return true;
}
